services:
  - docker

install:
  - docker build -t fasttree .

before_script:
  - git clone https://github.com/ddiez/dataset.git

script:
  - docker run fasttree
  - docker run -v $(pwd):/tmp fasttree FastTree /tmp/dataset/aln/uniprot.faln

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ddiez/fasttree;
    fi
